# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

env:
 global:
  - NGINX_VERSION=1.10.1
  - NPS_VERSION=1.11.33.2
  - OPENSSL_VERSION=1.0.2h

branches:
  except:
  - tmp

language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential zlib1g-dev libpcre3 libpcre3-dev unzip

install:
 - ./download-openssl
 - ./download-pagespeed
 - ./download-nginx
 - ./patch-nginx-spdy

script:
 - cd $HOME/nginx-${NGINX_VERSION}/
 - ./configure --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=%{_libdir}/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-http_spdy_module --with-http_v2_module --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed' --with-ipv6 --with-openssl=${HOME}/openssl-${OPENSSL_VERSION}
 - make
 - objs/nginx -V
 - cp objs/nginx $TRAVIS_BUILD_DIR
 - chmod 777 ${TRAVIS_BUILD_DIR}/nginx

compiler: gcc

before_deploy:
 - ls -la $TRAVIS_BUILD_DIR

deploy:
 provider: releases
 api-key: "${GITHUB_TOKEN}"
 skip_cleanup: true
 file: "${TRAVIS_BUILD_DIR}/nginx"
 overwrite: true
 on:
  tags: true
