language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential zlib1g-dev libpcre3 libpcre3-dev unzip

install:
 - ./download-pagespeed
 - ./download-nginx

script:
 - cd $HOME/nginx-${NGINX_VERSION}/
 - ./configure --add-module=$HOME/ngx_pagespeed-release-${NPS_VERSION}-beta ${PS_NGX_EXTRA_FLAGS}
 - make
 - sudo make install

env:
 global:
  - export NGINX_VERSION=1.10.1
  - export NPS_VERSION=1.11.33.2

compiler: gcc

deploy:
 provider: releases
 api-key: "ca0b48c95696649a986ea0e525b0714bac081142"
 file: "FILE TO UPLOAD"
 skip_cleanup: true
 on:
 tags: true
