# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

env:
 global:
  - NGINX_VERSION=1.10.1
  - NPS_VERSION=1.11.33.2
  - OPENSSL_VERSION=1.0.2h

branches:
  except:
  - tmp

language: cpp

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential zlib1g-dev libpcre3 libpcre3-dev unzip

install:
 - ./download-openssl
 - ./download-pagespeed
 - ./download-nginx
 - ./patch-nginx-spdy

script:
 - ./build-nginx
 - cp $HOME/nginx-${NGINX_VERSION}/objs/nginx $TRAVIS_BUILD_DIR
 - chmod 777 ${TRAVIS_BUILD_DIR}/nginx

before_deploy:
 - ls -la $TRAVIS_BUILD_DIR

deploy:
 provider: releases
 api-key: "${GITHUB_TOKEN}"
 skip_cleanup: true
 file: "${TRAVIS_BUILD_DIR}/nginx"
 overwrite: true
 on:
  tags: true
